"""add_failed_at_to_jobs

Revision ID: 2cf5e2bafa8f
Revises: 2504b99774c5
Create Date: 2026-05-08 17:11:40.290606

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cf5e2bafa8f"
down_revision: Union[str, Sequence[str], None] = "2504b99774c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("failed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "failed_at")
    # ### end Alembic commands ###
