"""add_file_name_to_documents

Revision ID: c3890ddba5ac
Revises: 2cf5e2bafa8f
Create Date: 2026-05-08 17:18:15.490203

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3890ddba5ac"
down_revision: Union[str, Sequence[str], None] = "2cf5e2bafa8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "file_name", sa.String(), server_default="''", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_name")
    # ### end Alembic commands ###
